#!/usr/bin/env bash

# fetch the colors
. "${HOME}/.cache/wal/colors.sh"

# vars
p="  "
barh="25"
barw=""
margin_w="0"
margin_h="0"

source ~/.bin/auth

rm ~/.spotitemp
pkill -f spotifycl
~/.bin/spotifycl status > ~/.spotitemp &

ensure_length ()
{
	size=${#1}
  for ((i=$2; i <= desired ; i++))
  do
    1="$1 "
  done
}

# functions
song() {
	playing="$(mpc status | grep -o 'playing' )"

	if [ "$playing" == "playing" ]; then
		echo "$p$(mpc current --format '%artist% - %title%')$p"
	fi
}

clock() {
	datetime="$(date "+%a %R")"
	echo "$datetime"
}

email() {
	email="$(/home/oscar/.bin/newmailcount)"
	if [ "$email" != "0" ]; then
		echo "$p$email$p"
	fi
}

spotify() {
	spoti="$(tail -n 1 ~/.spotitemp)";
	if [ "$spoti" != "" ]; then
		echo "$p$spoti$p"
	fi
}

# loops
loop-desktop() {
	while :; do
		echo "%{r}\
		%{B$color1}%{F$foreground}%{A:mpc toggle &:}$(song)%{A}\
		%{B$color1}%{A1:~/.bin/spotifycl save_remove &:}$(spotify)%{A1}\
		%{B$color6}%{F$background}$(email)\
		%{B$background}%{F$foreground}$p$(clock)$p"	
		sleep 0.1
	done |\
	
	lemonbar \
	    -f 'Roboto:size=9' \
			-g "${barw}x${barh}+${margin_w}+${margin_h}" \
	    -B "$background" -F "$foreground" \
		\
	    | bash
}

loop-desktop
