#!/usr/bin/bash
sed -i '/gtk-theme-name=/c\gtk-theme-name=Materia' ~/.config/gtk-3.0/settings.ini
sed -i '/gtk-theme-name=/c\gtk-theme-name="Materia"' ~/.gtkrc-2.0

export ACCENT="#3F51B5"
export BG="#eeeeee"
export FG="#1d1f22"

sed -e "/focused_workspace/c\focused_workspace $ACCENT $BG $FG
/client.focused/c\client.focused          $ACCENT $BG $FG $BG   $BG
/client.focused_inactive/c\client.focused_inactive $BG $BG $FG $BG   $BG
/client.unfocused/c\client.unfocused        $BG $BG $FG $BG   $BG
/client.urgent/c\client.urgent           $BG $ACCENT $FG $BG   $BG
/client.placeholder/c\client.placeholder      $BG $BG $FG $BG   $BG
/active_workspace/c\active_workspace $BG $BG $FG
/inactive_workspace/c\inactive_workspace $BG $BG $FG
/urgent_workspace/c\urgent_workspace $ACCENT $ACCENT $FG" ~/.config/i3/config-def > ~/.config/i3/config

i3-msg restart
feh --bg-scale ~/Pictures/Wallpapers/day.jpg
gtkreload
