#!/usr/bin/bash
rm ~/tf-custom/configs/cfg/mouse.cfg
rm ~/tf-custom/configs/cfg/addons.cfg

ln -s ~/tf-custom/configs/cfg/mouse-desktop.cfg ~/tf-custom/configs/cfg/mouse.cfg
ln -s ~/tf-custom/configs/cfg/addons-desktop.cfg ~/tf-custom/configs/cfg/addons.cfg
