#!/bin/sh

i3status | while :
do
	read line
	
	emailcount=$(~/.bin/newmailcount)
	if [ $? -eq 0 ]; then
		email="$emailcount |"
	else
		email=""
	fi
  	  
	taskcount=$(~/.bin/taskcount)
	if [ $? -eq 0 ]; then
		tasks="$taskcount | "
	else
		tasks=""
	fi

	echo "$tasks $email $line" || exit 1
done
