#!/usr/bin/bash
# gtk
wal -gR

# discord
~/.bin/wal-discord/wal-discord
if [ "$1" == "init" ]; then
	beautifuldiscord --css $HOME/.cache/wal-discord/style.css
fi

# pollen
sassc --style expanded ~/.bin/pollen/scss/style.scss ~/.bin/pollen/style.css

# spotify
sudo oomoxify-cli ~/.cache/wal/colors-oomox

if pgrep spotify; then
    pkill spotify
    spotify
fi

# steam
wal_steam
# don't kill steam cos that's a whole mess that's not worth getting involved in

# lemonbar
pkill lemonbar
if [ "$?" -eq 0 ]; then
	~/.bin/togglebar
fi
