#!/usr/bin/bash

PROJECTS_ROOT="$HOME/Projects"
PROJECT_NAME=$1
OPEN_ATOM=true
echo $1
echo $2

if [ "$PROJECT_NAME" = "--no-atom" ]; then
  PROJECT_NAME=$2
  OPEN_ATOM=false
fi
echo $OPEN_ATOM

PROJECT="$PROJECTS_ROOT/$PROJECT_NAME"


if [ ! -d "$PROJECT" ]; then
  echo "Couldn't find project"
else
  clear
  cd "$PROJECT"
  ansi ""
  echo "    $(ansi --bold --underline --cyan $PROJECT_NAME)"

  if [ -d "$PROJECT/.git" ]; then
    STAGED="$(git status --porcelain | grep -E "^A.|^M." | wc -l)"
    MODIFIED="$(git status --porcelain | grep -E "^.M" | wc -l)"
    ADDED="$(git status --porcelain | grep "^??" | wc -l)"

    ansi --blue     "     on $(git rev-parse --abbrev-ref HEAD)"
    ansi --green    "       $STAGED staged"
    ansi --yellow   "       $MODIFIED modified"
    ansi --magenta  "       $ADDED added"
  else
    ansi --red "      no git."
  fi


  if [ $OPEN_ATOM = true ]; then
    atom .
  else
    ansi --red "      not opening atom"
  fi
  ansi ""
fi

